services:
  app:
    volumes:
      - .:/app
    environment:
      DJANGO_ENV: dev
    ports:
      - "8000:8000"
      - "5678:5678"
    command: >
      python -m debugpy --listen 0.0.0.0:5678 --wait-for-client
      manage.py runserver 0.0.0.0:8000
