services:
  app:
    volumes:
      - .:/app
    environment:
      DJANGO_ENV: dev
    ports:
      - "8000:8000"
    command: gunicorn IOTPMV.asgi:application --bind 0.0.0.0:8000 --reload --log-level debug

