# Generated by Django 5.2 on 2025-05-08 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0111_alter_t_instru_contra_alter_t_instru_tipo_vincu'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 't_fase',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='t_compe',
            name='fase',
        ),
        migrations.RemoveField(
            model_name='t_compe',
            name='progra',
        ),
        migrations.CreateModel(
            name='T_compe_progra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_compe')),
                ('progra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_progra')),
            ],
            options={
                'db_table': 't_compe_progra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='T_compe_fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_compe')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_fase')),
            ],
            options={
                'db_table': 't_compe_fase',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='t_compe',
            name='fase',
            field=models.ManyToManyField(through='commons.T_compe_fase', to='commons.t_fase'),
        ),
        migrations.AddField(
            model_name='t_compe',
            name='progra',
            field=models.ManyToManyField(through='commons.T_compe_progra', to='commons.t_progra'),
        ),
    ]
