# Generated by Django 5.2 on 2025-05-15 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0112_t_fase_remove_t_compe_fase_remove_t_compe_progra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_fase_ficha',
            name='fase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_fase'),
        ),
        migrations.AlterField(
            model_name='t_instru',
            name='profe',
            field=models.CharField(choices=[('ingenieros', 'Ingeniero de sistemas'), ('ingenieroe', 'Ingeniero electronico'), ('ingenierosof', 'Ingeniero de software'), ('tecnologodf', 'Tecnologo en desarrollo de software')], max_length=200),
        ),
        migrations.AlterField(
            model_name='t_instru',
            name='tipo_vincu',
            field=models.CharField(choices=[('termino indefinido', 'Termino indefinido'), ('colaborador externo', 'Colaborador externo'), ('obra', 'Obra labor'), ('presta', 'Prestacion de Servicios'), ('sindefinir', 'Sin definir')], max_length=50),
        ),
    ]
