# Generated by Django 5.2 on 2025-05-17 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0113_alter_t_fase_ficha_fase_alter_t_instru_profe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_acti',
            name='fase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_fase'),
        ),
    ]
