# Generated by Django 5.2 on 2025-05-18 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0114_alter_t_acti_fase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_crono',
            name='nove',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
