# Generated by Django 5.2 on 2025-06-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0117_alter_t_raps_acti_rap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_ficha',
            name='num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
