# Generated by Django 5.2 on 2025-06-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0118_alter_t_ficha_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_acti',
            name='horas_auto',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_acti',
            name='horas_dire',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
