# Generated by Django 5.2 on 2025-06-09 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0119_t_acti_horas_auto_t_acti_horas_dire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_acti',
            name='guia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.t_guia'),
        ),
    ]
