# Generated by Django 5.2 on 2025-06-19 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0120_alter_t_acti_guia'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_raps_fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_fase')),
                ('rap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_raps')),
            ],
            options={
                'db_table': 't_raps_fase',
                'managed': True,
            },
        ),
    ]
