# Generated by Django 5.2 on 2025-06-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0121_t_raps_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_raps',
            name='fase',
            field=models.ManyToManyField(through='commons.T_raps_fase', to='commons.t_fase'),
        ),
    ]
