# Generated by Django 5.2 on 2025-06-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0123_alter_t_compe_fase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_compe',
            name='fase',
            field=models.ManyToManyField(blank=True, through='commons.T_compe_fase', to='commons.t_fase'),
        ),
    ]
