# Generated by Django 5.2 on 2025-07-07 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0124_alter_t_compe_fase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_apre',
            name='repre_legal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.t_repre_legal'),
        ),
        migrations.AlterField(
            model_name='t_perfil',
            name='tipo_dni',
            field=models.CharField(choices=[('ti', 'Tarjeta de identidad'), ('cc', 'Cédula de ciudadanía'), ('pp', 'Pasaporte'), ('ce', 'Cédula de extranjería'), ('ppt', 'Permiso por protección temporal')], max_length=50),
        ),
    ]
