# Generated by Django 5.2 on 2025-07-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0125_alter_t_apre_repre_legal_alter_t_perfil_tipo_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_perfil',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin'), ('instructor', 'Instructor'), ('aprendiz', 'Aprendiz'), ('lider', 'Lider'), ('gestor', 'Gestor'), ('consulta', 'Consulta')], max_length=50),
        ),
    ]
