# Generated by Django 5.2 on 2025-08-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0126_alter_t_perfil_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_apre',
            name='esta',
            field=models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('prematricula', 'Pre matricula'), ('desertado', 'Desertado'), ('sinficha', 'Sin Ficha')], max_length=200),
        ),
        migrations.AlterField(
            model_name='t_repre_legal',
            name='dire',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='t_repre_legal',
            name='mail',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='t_repre_legal',
            name='tele',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
