# Generated by Django 5.2 on 2025-08-05 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0127_alter_t_apre_esta_alter_t_repre_legal_dire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_apre',
            name='repre_legal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.t_repre_legal'),
        ),
    ]
