# Generated by Django 5.2 on 2025-08-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0128_alter_t_apre_repre_legal'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_compe',
            name='cod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='t_raps',
            name='cod',
            field=models.IntegerField(default=0),
        ),
    ]
