# Generated by Django 5.2 on 2025-08-19 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0129_t_compe_cod_t_raps_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_raps',
            name='progra',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.t_progra'),
        ),
        migrations.AlterField(
            model_name='t_compe',
            name='progra',
            field=models.ManyToManyField(blank=True, null=True, through='commons.T_compe_progra', to='commons.t_progra'),
        ),
    ]
