# Generated by Django 5.2 on 2025-08-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0130_t_raps_progra_alter_t_compe_progra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_compe',
            name='progra',
            field=models.ManyToManyField(blank=True, through='commons.T_compe_progra', to='commons.t_progra'),
        ),
    ]
