# Generated by Django 5.2 on 2025-08-22 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0132_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'managed': True, 'ordering': ['-timestamp'], 'verbose_name': 'Registro de auditoría', 'verbose_name_plural': 'Registros de auditoría'},
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='t_auditlog',
        ),
    ]
