# Generated by Django 5.2 on 2025-08-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0133_alter_auditlog_options_alter_auditlog_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='related_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='related_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
