# Generated by Django 5.2 on 2025-08-29 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0134_auditlog_related_id_auditlog_related_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_acti',
            name='fase',
        ),
        migrations.RemoveField(
            model_name='t_acti',
            name='guia',
        ),
        migrations.RemoveField(
            model_name='t_acti',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='t_acti_docu',
            name='acti',
        ),
        migrations.RemoveField(
            model_name='t_acti_descri',
            name='acti',
        ),
        migrations.RemoveField(
            model_name='t_raps_acti',
            name='acti',
        ),
        migrations.RemoveField(
            model_name='t_acti_ficha',
            name='acti',
        ),
        migrations.RemoveField(
            model_name='t_acti_apre',
            name='acti',
        ),
        migrations.RemoveField(
            model_name='t_acti_apre',
            name='apre',
        ),
        migrations.RemoveField(
            model_name='t_acti_descri',
            name='descri',
        ),
        migrations.RemoveField(
            model_name='t_acti_docu',
            name='docu',
        ),
        migrations.RemoveField(
            model_name='t_acti_recu',
            name='acti_docu',
        ),
        migrations.RemoveField(
            model_name='t_acti_ficha',
            name='crono',
        ),
        migrations.RemoveField(
            model_name='t_acti_ficha',
            name='ficha',
        ),
        migrations.RemoveField(
            model_name='t_cali',
            name='acti',
        ),
        migrations.RemoveField(
            model_name='t_acti_recu',
            name='recu',
        ),
        migrations.RemoveField(
            model_name='t_cali',
            name='apre',
        ),
        migrations.RemoveField(
            model_name='t_crite_eva',
            name='guia',
        ),
        migrations.RemoveField(
            model_name='t_docu_proce',
            name='docu',
        ),
        migrations.RemoveField(
            model_name='t_guia',
            name='progra',
        ),
        migrations.RemoveField(
            model_name='t_guia_docu',
            name='guia',
        ),
        migrations.RemoveField(
            model_name='t_guia_docu',
            name='docu',
        ),
        migrations.RemoveField(
            model_name='t_nove',
            name='sub_tipo',
        ),
        migrations.RemoveField(
            model_name='t_nove',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='t_nove_ficha',
            name='nove',
        ),
        migrations.RemoveField(
            model_name='t_nove_docu',
            name='nove',
        ),
        migrations.RemoveField(
            model_name='t_nove_docu',
            name='docu',
        ),
        migrations.RemoveField(
            model_name='t_nove_ficha',
            name='ficha',
        ),
        migrations.RemoveField(
            model_name='t_raps_acti',
            name='rap',
        ),
        migrations.RemoveField(
            model_name='t_raps_ficha',
            name='fase',
        ),
        migrations.RemoveField(
            model_name='t_raps_ficha',
            name='ficha',
        ),
        migrations.RemoveField(
            model_name='t_raps_ficha',
            name='rap',
        ),
        migrations.RemoveField(
            model_name='t_subtipo_nove',
            name='tipo',
        ),
        migrations.CreateModel(
            name='T_jui_eva_actu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_repor', models.DateField()),
                ('eva', models.CharField(max_length=20)),
                ('fecha_eva', models.DateField(blank=True, null=True)),
                ('apre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_apre')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_ficha')),
                ('instru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.t_instru')),
                ('rap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_raps')),
            ],
            options={
                'db_table': 't_jui_eva_actu',
            },
        ),
        migrations.CreateModel(
            name='T_jui_eva_diff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambi', models.CharField(choices=[('nuevo', 'Nuevo registro'), ('actualizado', 'Actualización'), ('eliminado', 'Eliminado')], max_length=20)),
                ('descri', models.TextField(blank=True, null=True)),
                ('fecha_diff', models.DateTimeField(auto_now_add=True)),
                ('apre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='commons.t_perfil')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='commons.t_ficha')),
                ('instru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_instructor', to='commons.t_perfil')),
                ('jui', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.t_jui_eva_actu')),
            ],
            options={
                'db_table': 't_jui_eva_diff',
            },
        ),
        migrations.DeleteModel(
            name='T_tipo_acti',
        ),
        migrations.DeleteModel(
            name='T_acti',
        ),
        migrations.DeleteModel(
            name='T_acti_apre',
        ),
        migrations.DeleteModel(
            name='T_acti_descri',
        ),
        migrations.DeleteModel(
            name='T_descri',
        ),
        migrations.DeleteModel(
            name='T_acti_docu',
        ),
        migrations.DeleteModel(
            name='T_crono',
        ),
        migrations.DeleteModel(
            name='T_acti_ficha',
        ),
        migrations.DeleteModel(
            name='T_acti_recu',
        ),
        migrations.DeleteModel(
            name='T_recu',
        ),
        migrations.DeleteModel(
            name='T_cali',
        ),
        migrations.DeleteModel(
            name='T_crite_eva',
        ),
        migrations.DeleteModel(
            name='T_docu_proce',
        ),
        migrations.DeleteModel(
            name='T_guia',
        ),
        migrations.DeleteModel(
            name='T_guia_docu',
        ),
        migrations.DeleteModel(
            name='T_nove',
        ),
        migrations.DeleteModel(
            name='T_nove_docu',
        ),
        migrations.DeleteModel(
            name='T_nove_ficha',
        ),
        migrations.DeleteModel(
            name='T_raps_acti',
        ),
        migrations.DeleteModel(
            name='T_raps_ficha',
        ),
        migrations.DeleteModel(
            name='T_subtipo_nove',
        ),
        migrations.DeleteModel(
            name='T_tipo_nove',
        ),
        migrations.AddIndex(
            model_name='t_jui_eva_actu',
            index=models.Index(fields=['ficha', 'apre', 'rap'], name='t_jui_eva_a_ficha_i_05c029_idx'),
        ),
        migrations.AddIndex(
            model_name='t_jui_eva_actu',
            index=models.Index(fields=['fecha_repor'], name='t_jui_eva_a_fecha_r_c0eaad_idx'),
        ),
        migrations.AddIndex(
            model_name='t_jui_eva_diff',
            index=models.Index(fields=['ficha', 'apre', 'tipo_cambi'], name='t_jui_eva_d_ficha_i_486bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='t_jui_eva_diff',
            index=models.Index(fields=['fecha_diff'], name='t_jui_eva_d_fecha_d_5afe56_idx'),
        ),
    ]
