# Generated by Django 5.2 on 2025-08-29 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0135_remove_t_acti_fase_remove_t_acti_guia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_jui_eva_diff',
            name='apre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='commons.t_apre'),
        ),
        migrations.AlterField(
            model_name='t_jui_eva_diff',
            name='instru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_instructor', to='commons.t_instru'),
        ),
    ]
