# Generated by Django 5.2 on 2025-08-29 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0136_alter_t_jui_eva_diff_apre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_jui_eva_diff',
            name='apre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.t_apre'),
        ),
        migrations.AlterField(
            model_name='t_jui_eva_diff',
            name='ficha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_ficha'),
        ),
        migrations.AlterField(
            model_name='t_jui_eva_diff',
            name='instru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.t_instru'),
        ),
    ]
