# Generated by Django 5.2 on 2025-09-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0137_alter_t_jui_eva_diff_apre_alter_t_jui_eva_diff_ficha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_raps',
            name='nom',
            field=models.CharField(max_length=300),
        ),
    ]
