# Generated by Django 5.2 on 2025-09-05 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0138_alter_t_raps_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_permi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modu', models.CharField(choices=[('fichas', 'Fichas'), ('instituciones', 'Instituciones'), ('reportes', 'Reportes'), ('usuarios', 'Usuarios')], max_length=100)),
                ('acci', models.CharField(choices=[('ver', 'Ver'), ('editar', 'Editar'), ('eliminar', 'Eliminar')], max_length=50)),
                ('filtro', models.JSONField(blank=True, null=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='commons.t_perfil')),
            ],
            options={
                'db_table': 't_permi',
                'unique_together': {('perfil', 'modu', 'acci')},
            },
        ),
    ]
