# Generated by Django 5.2 on 2025-09-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0139_t_permi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_permi',
            name='modu',
            field=models.CharField(choices=[('fichas', 'Fichas'), ('instituciones', 'Instituciones'), ('aprendices', 'Aprendices'), ('instructores', 'Instructores'), ('admin', 'Administradores'), ('lideres', 'Lideres'), ('gestores', 'Gestores'), ('cuentas', 'Cuentas'), ('programas', 'Programas'), ('documentos', 'Documentos'), ('cronogramas', 'Cronogramas'), ('reportes', 'Reportes'), ('usuarios', 'Usuarios')], max_length=100),
        ),
    ]
