# Generated by Django 5.2 on 2025-09-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0140_alter_t_permi_modu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_permi',
            name='modu',
            field=models.CharField(choices=[('departamentos', 'Departamentos'), ('municipios', 'Municipios'), ('usuarios', 'Usuarios'), ('instructores', 'Instructores'), ('aprendices', 'Aprendices'), ('admin', 'Administradores'), ('lideres', 'Lideres'), ('cuentas', 'Cuentas'), ('gestores', 'Gestores'), ('fichas', 'Fichas'), ('portafolios', 'Portafolios'), ('instituciones', 'Instituciones'), ('centros', 'Centros de Formacion'), ('programas', 'Programas'), ('competencias', 'Competencias'), ('raps', 'Raps')], max_length=100),
        ),
    ]
