# Generated by Django 5.2 on 2025-09-26 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0141_alter_t_permi_modu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T_porta_archi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eli_en', models.DateTimeField(auto_now_add=True)),
                ('obser', models.CharField(max_length=500)),
                ('ubi', models.CharField(max_length=500)),
                ('docu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.t_docu')),
                ('eli_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='archivos_eliminados', to='commons.t_ficha')),
            ],
            options={
                'db_table': 't_porta_archi',
            },
        ),
    ]
