# Generated by Django 5.2 on 2025-10-03 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('commons', '0144_alter_t_permi_modu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T_acci_nove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descri', models.CharField(max_length=2000)),
                ('crea_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='acciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_acci_nove',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='T_acci_nove_docu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acci_nove', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_acci_nove')),
                ('docu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.t_docu')),
            ],
            options={
                'db_table': 't_acci_nove_docu',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='T_nove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('esta', models.CharField(choices=[('nuevo', 'Nuevo'), ('en_curso', 'En_curso'), ('pendiente', 'Pendiente'), ('planificacion', 'Planificacion'), ('terminado', 'Terminado'), ('rechazado', 'Rechazado'), ('cerrado', 'Cerrado'), ('reabierto', 'Reabierto')], default='nuevo', max_length=50)),
                ('motivo_solucion', models.CharField(blank=True, choices=[('exito', 'Exito'), ('cierre_cliente', 'Cierre_cliente'), ('exito_problemas', 'Exito_problemas'), ('cancelado_soporte', 'Cancelado_soporte'), ('accion_otro_proveedor', 'Accion_otro_proveedor'), ('accion_solicitante', 'Accion_solicitante'), ('cronograma', 'Cronograma'), ('en_curso', 'En_curso')], max_length=50, null=True)),
                ('descri', models.CharField(max_length=2000)),
                ('tipo', models.CharField(blank=True, choices=[('incidencia', 'Incidencia'), ('requerimiento', 'Requerimiento'), ('consulta', 'Consulta'), ('sugerencia', 'Sugerencia')], max_length=50, null=True)),
                ('fecha_regi', models.DateTimeField(auto_now_add=True)),
                ('fecha_venci', models.DateTimeField(blank=True, null=True)),
                ('fecha_ulti_acci', models.DateTimeField(blank=True, null=True)),
                ('cie_ace_por_soli', models.BooleanField(default=False)),
                ('respo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_responsable', to=settings.AUTH_USER_MODEL)),
                ('respo_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='novedades_group', to='auth.group')),
                ('soli', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_nove',
                'ordering': ['-fecha_venci'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='t_acci_nove',
            name='nove',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='commons.t_nove'),
        ),
        migrations.CreateModel(
            name='T_nove_docu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.t_docu')),
                ('nove', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_nove')),
            ],
            options={
                'db_table': 't_nove_docu',
                'managed': True,
            },
        ),
    ]
