# Generated by Django 5.2 on 2025-10-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0145_t_acci_nove_t_acci_nove_docu_t_nove_t_acci_nove_nove_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_acci_nove',
            name='descri',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='t_nove',
            name='descri',
            field=models.TextField(),
        ),
    ]
