# Generated by Django 5.2 on 2025-10-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0146_alter_t_acci_nove_descri_alter_t_nove_descri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_nove',
            name='num',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
