# Generated by Django 5.2 on 2025-10-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0147_alter_t_nove_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ficha',
            name='vige',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
