# Generated by Django 5.2 on 2025-10-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0148_t_ficha_vige'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_apre',
            name='esta',
            field=models.CharField(choices=[('activo', 'Activo'), ('suspendido', 'Suspendido'), ('retirov', 'Retiro voluntario'), ('prematricula', 'Pre matricula'), ('desertado', 'Desertado'), ('sinficha', 'Sin Ficha')], max_length=200),
        ),
    ]
