# Generated by Django 5.2 on 2025-11-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0149_alter_t_apre_esta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_ficha',
            name='vige',
            field=models.CharField(default='2025', max_length=20),
        ),
    ]
