# Generated by Django 5.2 on 2025-11-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0150_alter_t_ficha_vige'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_permi',
            name='acci',
            field=models.CharField(choices=[('ver', 'Ver'), ('verinstructor', 'Ver Instructor'), ('editar', 'Editar'), ('eliminar', 'Eliminar')], max_length=50),
        ),
    ]
