# Generated by Django 5.2 on 2025-11-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0152_auditlog_t_auditlog_content_858fea_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_jui_eva_actu',
            name='fecha_eva',
        ),
        migrations.RemoveField(
            model_name='t_jui_eva_actu',
            name='instru',
        ),
        migrations.RemoveField(
            model_name='t_jui_eva_diff',
            name='instru',
        ),
    ]
