# Generated by Django 5.2 on 2026-04-13 03:13

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0153_remove_t_jui_eva_actu_fecha_eva_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='t_documentfolder',
            name='oculto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='t_documentfolder',
            name='roles_editables',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_documentfolder',
            name='roles_visibles',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_ficha',
            name='corte',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='T_PlantillaAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_plantilla_admin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='T_PlantillaNodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('orden', models.IntegerField(default=0)),
                ('roles_visibles', models.JSONField(blank=True, null=True)),
                ('roles_editables', models.JSONField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_crea', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantilla_children', to='commons.t_plantillanodo')),
                ('usuario_crea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_plantilla_nodo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='T_PlantillaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('snapshot', models.JSONField()),
                ('descripcion', models.CharField(max_length=500)),
                ('auto_aplicar_nuevas', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_plantilla_version',
                'ordering': ['-version'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='T_PlantillaAplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=50)),
                ('detalle', models.JSONField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_ficha')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.t_plantillaversion')),
            ],
            options={
                'db_table': 't_plantilla_aplicacion',
                'ordering': ['-fecha'],
                'managed': True,
            },
        ),
    ]
