# Generated by Django 5.2 on 2026-04-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0154_t_documentfolder_oculto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ficha',
            name='carpetas_desincronizadas',
            field=models.BooleanField(default=False),
        ),
    ]
