# Generated by Django 5.2 on 2026-04-22 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0155_t_ficha_carpetas_desincronizadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('sistemas', 'Sistemas'), ('contable', 'Contable'), ('direccion', 'Dirección'), ('rrhh', 'RRHH')], max_length=20)),
                ('nivel_acceso', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=20)),
                ('esta', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='commons.t_perfil')),
            ],
            options={
                'db_table': 't_consulta',
                'managed': True,
            },
        ),
    ]
