# Generated by Django 5.2 on 2026-05-12 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0157_t_permi_modu_seguimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_porta_archi',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='t_porta_archi',
            name='aprendiz',
            field=models.ForeignKey(blank=True, help_text='Si se elimino del portafolio del aprendiz, se guarda aqui', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='papelera', to='commons.t_apre'),
        ),
        migrations.AddField(
            model_name='t_porta_archi',
            name='nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre original del nodo eliminado', max_length=255),
        ),
        migrations.AddField(
            model_name='t_porta_archi',
            name='parent_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID del nodo padre original (None si era raiz)', null=True),
        ),
        migrations.AddField(
            model_name='t_porta_archi',
            name='restaurado',
            field=models.BooleanField(default=False, help_text='Si ya fue restaurado, no se puede restaurar de nuevo'),
        ),
        migrations.AddField(
            model_name='t_porta_archi',
            name='restaurado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_porta_archi',
            name='restaurado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papelera_restaurada', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='t_porta_archi',
            name='tipo',
            field=models.CharField(choices=[('carpeta', 'Carpeta'), ('documento', 'Documento')], default='documento', help_text='Si era carpeta o documento', max_length=20),
        ),
    ]
