# Generated by Django 5.2 on 2026-05-13 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alertas_y_notificaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='user',
        ),
        migrations.RenameIndex(
            model_name='t_notifi',
            new_name='t_notifi_usuario_a8d23c_idx',
            old_name='t_notifi_usuario_leida_idx',
        ),
        migrations.RenameIndex(
            model_name='t_notifi',
            new_name='t_notifi_origen__27e1d7_idx',
            old_name='t_notifi_origen_idx',
        ),
        migrations.DeleteModel(
            name='tasks',
        ),
    ]
