# Generated by Django 5.2 on 2026-05-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0158_t_porta_archi_papelera'),
        ('tasks', '0004_limpieza_modelo_tasks_huerfano'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_alerta_regla',
            name='destinatarios_cc',
            field=models.ManyToManyField(blank=True, help_text='Perfiles que reciben copia (CC): enlaces territoriales, equipo de portafolio, apoyo administrativo.', related_name='alertas_destino_cc', to='commons.t_perfil'),
        ),
    ]
