# Generated by Django 5.2 on 2026-05-14 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alerta_regla_destinatarios_cc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='t_notifi',
            name='resuelta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='t_notifi',
            name='resuelta_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_notifi',
            name='resuelta_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_resueltas', to=settings.AUTH_USER_MODEL),
        ),
    ]
